/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
// int _cxa_finalize(void *);
// int puts(const char *s);
// int strcmp(const char *s1, const char *s2);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
char *deregister_tm_clones();
__int64 register_tm_clones();
char *_do_global_dtors_aux();
__int64 frame_dummy(); // weak
int __fastcall main(int argc, const char **argv, const char **envp);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
char key[9] = "nAs42O2S"; // weak
char pattern[40] =
{
  '&',
  '\x16',
  'B',
  '\x06',
  'I',
  '\'',
  'e',
  'c',
  '1',
  'y',
  '&',
  '`',
  'm',
  '\x18',
  '[',
  '\a',
  '&',
  '\x1E',
  '\x01',
  '\a',
  'd',
  '|',
  '`',
  ' ',
  '\v',
  '\x1E',
  '\x16',
  'z',
  '\v',
  '~',
  '|',
  '\x16',
  ']',
  '3',
  '\x1A',
  'Z',
  'u',
  '2',
  '\0',
  '\0'
}; // weak
int flag_len = 38; // weak
int key_len = 8; // weak
char _bss_start; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 40A8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
  sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 108A: positive sp value 8 has been found
// 1091: variable 'v3' is possibly undefined

//----- (00000000000010B0) ----------------------------------------------------
char *deregister_tm_clones()
{
  return &_bss_start;
}
// 4070: using guessed type char _bss_start;

//----- (00000000000010E0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}

//----- (0000000000001120) ----------------------------------------------------
char *_do_global_dtors_aux()
{
  char *result; // rax

  if ( !_bss_start )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 4070: using guessed type char _bss_start;

//----- (0000000000001160) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 1160: using guessed type __int64 frame_dummy();

//----- (0000000000001169) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  int i; // [rsp+1Ch] [rbp-4h]

  if ( argc == 2 )
  {
    for ( i = 0; i < flag_len; ++i )
      pattern[i] ^= key[i % key_len];
    if ( !strcmp(argv[1], pattern) )
      puts("Congratulations! You found the flag!");
    else
      puts("Haha! wrong >:)!!!!!!");
    return 0;
  }
  else
  {
    puts("Usage: ./chal.exe <flag>");
    return 1;
  }
}
// 4068: using guessed type int flag_len;
// 406C: using guessed type int key_len;

//----- (0000000000001230) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=19 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
